name: gsc_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  shared_preferences: ^2.0.15
  xml2json: ^5.3.6
  flutter_easyloading: ^3.0.2
  intl: ^0.17.0
  youtube_player_iframe: ^4.0.4
  provider: ^6.0.3
  http: ^0.13.5
  qr_flutter: ^4.0.0
  flutter_datetime_picker: ^1.3.2
  dropdown_button2: ^1.9.0
  pinput: ^2.2.5
  webview_flutter: ^4.0.7
  url_launcher: ^6.1.10
  cached_network_image: ^3.1.0
  flutter_inappwebview: ^5.7.2+3
  geolocator: ^9.0.2
  flutter_slidable: ^2.0.0
  firebase_remote_config: ^3.0.15
  firebase_analytics: ^10.1.6
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^9.9.1
  package_info_plus: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  dotted_decoration: ^2.0.0
  scrollable_positioned_list: ^0.2.3
  device_info_plus: ^7.0.0
  flutter_html: ^3.0.0-alpha.3
  # facebook_app_events: ^0.17.0
  location: ^4.4.0
  huawei_push: ^6.10.0+300
  google_api_availability: ^3.0.1
  huawei_analytics: ^6.9.0+302


flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/appicon/GSC app_icon_1024.png"
  image_path_ios: "assets/images/appicon/GSC app_icon_1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/images/appicon/GSC app_icon_1024.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images//appicon/GSC app_icon_1024.png" # only available for Android 8.0 devices and above


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/locale/
    - assets/html/
    - assets/javascript/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold_0.ttf
        - asset: fonts/Poppins-Light_0.ttf
        - asset: fonts/Poppins-Medium_0.ttf
        - asset: fonts/Poppins-Regular_0.ttf
        - asset: fonts/Poppins-SemiBold_0.ttf
        - asset: fonts/Poppins-Thin_0.ttf
    - family: Orbitron    
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
