// ignore_for_file: constant_identifier_names

class AnalyticsConstants {
  static const String ANALYTICS_SPLASH_SCREEN = "SPLASH_SCREEN";
  static const String ANALYTICS_HOME_SCREEN = "HOME_SCREEN";

  static const String ANALYTICS_LOGIN_SCREEN = "LOGIN_SCREEN";
  static const String ANALYTICS__FIRST_TIME_LOGIN_SCREEN =
      "FIRST_TIME_LOGIN_SCREEN";

  static const String ANALYTICS_FnB_SCREEN = "FnB_SCREEN";

  static const String ANALYTICS_SIGN_UP_SCREEN = "SIGN_UP_SCREEN";
  static const String ANALYTICS_SETTING_SCREEN = "SETTING_SCREEN";
  static const String ANALYTICS_DELETE_ACCOUNT_SCREEN = "DELETE_ACCOUNT_SCREEN";
  static const String ANALYTICS_CHANGE_PWD_SCREEN = "CHANGE_PWD_SCREEN";
  static const String ANALYTICS_REWARD_LISTING_SCREEN = "REWARD_LISTING_SCREEN";
  static const String ANALYTICS_REWARD_ITEM_DETAILS_SCREEN =
      "REWARD_ITEM_DETAILS_SCREEN";

  static const String ANALYTICS_REVIEW_SUMMARY_SCREEN = "REVIEW_SUMMARY_SCREEN";
  static const String ANALYTICS_QR_MEMBER_SCREEN = "QR_MEMBER_SCREEN";

  static const String ANALYTICS_PAYMENT_GATEWAY_SCREEN =
      "PAYMENT_GATEWAY_SCREEN";
  static const String ANALYTICS_ECOMBO_SELECTION_SCREEN =
      "ECOMBO_SELECTION_SCREEN";
  static const String ANALYTICS_DONE_TRANSACTION_SCREEN =
      "DONE_TRANSACTION_SCREEN";
  static const String ANALYTICS_TICKET_SELECTION_SCREEN =
      "TICKET_SELECTION_SCREEN";
  static const String ANALYTICS_PROFILE_SCREEN = "PROFILE_SCREEN";
  static const String ANALYTICS_GSCOIN_TRANSACTION_LIST_SCREEN =
      "GSCOIN_TRANSACTION_LIST_SCREEN";
  static const String ANALYTICS_FAVOURITE_CINEMA_LIST_SCREEN =
      "FAVOURITE_CINEMA_LIST_SCREEN";
  static const String ANALYTICS_EDIT_PROFILE_SCREEN =
      "FAVOURITE_EDIT_PROFILE_SCREEN";
  static const String ANALYTICS_ADD_FAVOURITE_CINEMA_SCREEN =
      "ADD_FAVOURITE_CINEMA_SCREEN";
  static const String ANALYTICS_RESET_PWD_SCREEN = "RESET_PWD_SCREEN";
  static const String ANALYTICS_FORGOT_PWD_SCREEN = "FORGOT_PWD_SCREEN";

  static const String ANALYTICS_OTP_SCREEN = "OTP_SCREEN";

  static const String ANALYTICS_TICKET_LIST_SCREEN = "TICKET_LIST_SCREEN";
  static const String ANALYTICS_TICKET_DETAILS_SCREEN = "TICKET_DETAILS_SCREEN";
  static const String ANALYTICS_TICKET_QR_SCREEN = "TICKET_QR_SCREEN";

  static const String ANALYTICS_SELECT_MOVIES_BY_OPSDATE_SCREEN =
      "SELECT_MOVIES_BY_OPSDATE_SCREEN";
  static const String ANALYTICS_MOVIE_DETAILS_SCREEN = "MOVIE_DETAILS_SCREEN";
  static const String ANALYTICS_SELECT_SEAT_SCREEN = "SELECT_SEAT_SCREEN";
  static const String ANALYTICS_MOVIES_LIST_SCREEN = "MOVIES_LIST_SCREEN";

  static const String ANALYTICS_SELECT_MOVIES_BY_OPSDATE_AURUM_SCREEN =
      "SELECT_MOVIES_BY_OPSDATE_AURUM_SCREEN";
  static const String ANALYTICS_ECOMBO_SELECTION_AURUM_SCREEN =
      "ECOMBO_SELECTION_AURUM_SCREEN";

  static const String ANALYTICS_CINEMA_LIST_SCREEN = "CINEMA_LIST_SCREEN";
  static const String ANALYTICS_SELECT_MOVIES_BY_CINEMA_SCREEN =
      "SELECT_MOVIES_BY_CINEMA_SCREEN";

  static const String ANALYTICS_FAST_TICKET_SCREEN = "MOVIE_DETAILS_SCREEN";
  static const String ANALYTICS_FAST_TICKET_CINEMA_SELECTION_SCREEN =
      "FAST_TICKET_CINEMA_SELECTION_SCREEN";
  static const String ANALYTICS_FAST_TICKET_MOVIE_SELECTION_SCREEN =
      "FAST_TICKET_MOVIE_SELECTION_SCREEN";

  static const String ANALYTICS_MESSAGE_DETAILS_SCREEN =
      "MESSAGE_DETAILS_SCREEN";
  static const String ANALYTICS_MESSAGE_LIST_SCREEN = "MESSAGE_LIST_SCREEN";

  static const String ANALYTICS_PROMOTION_LIST_SCREEN = "PROMOTION_LIST_SCREEN";
  static const String ANALYTICS_EXPERIENCE_LIST_SCREEN =
      "EXPERIENCE_LIST_SCREEN";
}
